Test the pwd deployment

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -72,11 +72,8 @@ jobs:
             echo "MONGODB_URI=$MONGO_URI" > .env
             cat .env
 
-            echo "🐳 Docker logina"
-            echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
-            echo "Docker success"
-
-
+            echo "🐳 Docker login"
+            echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin || { echo "❌ Docker login failed"; exit 1; }
 
       - name: 🚀 SSH - Deploy stack on PWD
         uses: appleboy/ssh-action@v0.1.10
