Test the pwd deployment

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -72,9 +72,9 @@ jobs:
             echo "MONGODB_URI=$MONGO_URI" > .env
             cat .env
 
-            echo "🐳 Docker logina"
-            echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
-            docker info | grep Username || { echo "❌ Docker login failed"; exit 1; }
+            echo "🐳 Docker login"
+            echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin || { echo "❌ Docker login failed"; exit 1; }
+
 
 
 
